# Generated by Django 5.1.3 on 2024-11-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_transaction_statistics_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionStatistics',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_transactions', models.IntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=25)),
                ('total_gained', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
            options={
                'db_table': 'transaction_statistics',
                'managed': False,
            },
        ),
    ]
