# Generated by Django 5.1.3 on 2024-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_etljob_materializedviewrefresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etljob',
            name='job_name',
            field=models.CharField(max_length=200),
        ),
    ]
