server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: etl_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: etl_logs
          app: neo_challenge
          env: development
          __path__: /var/log/etl/*.log
    pipeline_stages:
      - json:
          expressions:
            processor_type: processor_type
            error_type: error_type
            error_message: error_message
            row_index: row_index
      - labels:
          processor_type:
          error_type:
          row_index: