global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics/'

  - job_name: 'celery'
    static_configs:
      - targets: ['neo_challenge_celery:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s