class APIErrorMessages:
    INVALID_CLIENT_ID = 'Invalid client_id'
    USER_NOT_FOUND = 'User does not exist'
    INVALID_CREDENTIALS = 'Invalid username or password.'
    INTERNAL_SERVER_ERROR = 'Internal Server Error'
    INVALID_INPUT = 'Invalid input'
    USERNAME_EXISTS = 'A user with this username already exists.'
    PASSWORD_TOO_SHORT = 'Password must be at least 8 characters long.'
    INVALID_DATE_FORMAT = 'Invalid date format. Please use YYYY-MM-DD.'
    START_DATE_BEFORE_END_DATE = 'start_date must be before end_date.'
    INVALID_QUERY_PARAMS = 'Invalid query parameters'